server:
  port: 8091

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #          issuer-uri: http://localhost:8080/auth/realms/appsdeveloperblog
          jwk-set-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/certs
