spring:
  application:
    name: intro-to-spring-boot
  output:
    ansi:
      enabled: always
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
