spring:
  application:
    name: currency-exchange
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8000
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
