sfg:
  brewery:
    beer-inventory-service-host: http://localhost:8082
spring:
  datasource:
    initialization-mode: embedded
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
  cache:
    jcache:
      config: classpath:ehcache.xml
  h2:
    console:
      enabled: true
