spring:
  flyway:
    enabled: true
    password: example
    user: test
    url: jdbc:postgresql://localhost:5432/
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    hikari:
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/beerservice
    username: beer_service_user
    password: beer_service_password
logging:
  level:
    guru.springframework: DEBUG
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    org.hibernate.sql: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
