apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
    - image: alexunc/test
      jib: {}
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
      - target/classes/META-INF/dekorate/*.json
      - k8s/*.yaml
