server:
  port: 8087
spring:
  security:
    oauth2:
      client:
        registration:
          webclient:
            client-id: photo-app-code-flow-client
            client-secret: 6bc7863e-4dd8-4d7d-9951-e4213b18b6ff
            scope:
              - openid
              - profile
              - roles
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8087/login/oauth2/code/webclient
        provider:
          webclient:
            authorization-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/token
            jwk-set-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/certs
            user-info-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/userinfo
            user-nameattribute: preferred_username


