server:
  port: 8087
spring:
  security:
    oauth2:
      client:
        registration:
          webclient:
            client-id: web-client
            client-secret:
            scope:
              - openid
              - profile
              - roles
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8087/login/oauth2/code/webclient

