server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
