server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: users-status-check
          uri: lb://demo-resource-service
          predicates:
            - Path=/users/status/check
            - Method=GET
          fiilters:
            - RemoveRequestHeader=Cookie

        - id: albums
          uri: lb://albums-resource-server
          predicates:
            - Path=/albums
            - Method=GET
          fiilters:
            - RemoveRequestHeader=Cookie

        - id: photos
          uri: lb://photos-resource-server
          predicates:
            - Path=/photos
            - Method=GET
          fiilters:
            - RemoveRequestHeader=Cookie

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
