server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: users-status-check
          uri: http://localhost:8081
          predicates:
            - Path=/users/status/check
            - Method=GET
          fiilters:
            - RemoveRequestHeader=Cookie

        - id: albums
          uri: http://localhost:8091
          predicates:
            - Path=/albums
            - Method=GET
          fiilters:
            - RemoveRequestHeader=Cookie

        - id: photos
          uri: http://localhost:8092
          predicates:
            - Path=/photos
            - Method=GET
          fiilters:
            - RemoveRequestHeader=Cookie
