POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "john@doe.com",
  "password": "Qwerty12345"
}

###

POST http://localhost:8000/api/register
Content-Type: application/json

{
  "email": "john@doe.com",
  "password": "Qwerty12345",
  "password_confirm": "Qwerty12345"
}

###

POST http://localhost:8000/api/user
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzU3MDQyMTMsImlzcyI6IjEifQ.hXQ9We_qPtv1GYdKC8Jfm08tfBp8LCdLxRdObfE7LLo;

