version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: go_auth
      POSTGRES_USER: gorm_user
      POSTGRES_PASSWORD: gorm_password
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
