GET http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/auth?client_id=photo-app-code-flow-client&response_type=code&scope=openid%20profile&redirect_uri=http://localhost:8083/callback&state=asdasd
Accept: application/json

###
