POST http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&client_id=photo-app-code-flow-client&client_secret=6bc7863e-4dd8-4d7d-9951-e4213b18b6ff&code=7cf3d1be-aa43-41ef-9914-9219df3e38d2.69c4fc41-162e-4b71-99fa-f422fe7f924b.50d08e16-4407-4b49-8eea-cf7341895723&redirect_uri=http://localhost:8083/callback
###
